import os
import time
import threading
import queue
from bs4 import BeautifulSoup
from pymongo import MongoClient
import google.generativeai as genai
from dotenv import load_dotenv
import re
import urllib.parse
import json

# Stealth scraper bypass for NextJS CSR + WAF
import undetected_chromedriver as uc
from selenium.webdriver.common.by import By

# Load environment variables
load_dotenv()

MONGO_URL = os.getenv("MONGO_URL")
WEBSITE_URL = os.getenv("WEBSITE_URL")

# Load comma-separated Gemini keys
GEMINI_KEYS = [k.strip() for k in os.getenv("GEMINI_API_KEY", "").split(",") if k.strip()]
CURRENT_KEY_IDX = 0

if GEMINI_KEYS:
    genai.configure(api_key=GEMINI_KEYS[CURRENT_KEY_IDX])
    model = genai.GenerativeModel('gemini-2.5-flash')

BASE_URL = "https://www.india.gov.in"

def get_db_collection():
    client = MongoClient(MONGO_URL)
    db = client["government_schemes_db"]
    collection = db["detailed_schemes"]
    
    # Try creating index, fail silently if already exists
    try:
        collection.create_index(
            [
                ("name", "text"), ("description", "text"), 
                ("benefits", "text"), ("industry_tags", "text"),
                ("target_audience_tags", "text"), ("category_tags", "text")
            ],
            weights={
                "name": 10, "industry_tags": 8, "target_audience_tags": 8,
                "description": 5, "benefits": 5, "category_tags": 3
            },
            name="scheme_search_index"
        )
    except:
        pass
    
    return collection

def scrape_sitemap_schemes(collection):
    """
    Since the categories route is dynamically generated by MyScheme APIs and WAF blocked,
    the best and most complete way to find ALL schemas structurally is by pulling directly 
    from the publicly exported Scheme sitemap. 
    """
    print("[*] Accessing exact schemes directly via parent API sitemaps...")
    
    sitemap_url = "https://www.myscheme.gov.in/sitemap-1.xml" # usually schemas are here
    import requests
    
    # Check all valid sitemaps logic
    found_urls = set()
    for s_map in ['sitemap.xml', 'sitemap-0.xml', 'sitemap-1.xml']:
        try:
            r = requests.get(f"https://www.myscheme.gov.in/{s_map}", headers={'User-Agent': 'Mozilla/5.0'})
            links = re.findall(r'<loc>(.*?)</loc>', r.text)
            for link in links:
                if '/schemes/' in link:
                    found_urls.add(link)
        except Exception:
            continue
            
    print(f"[*] Successfully bypassed WAF via sitemaps. Found {len(found_urls)} unique scheme URLs.")
    return list(found_urls)


def extract_urls(browser, collection, url_queue):
    """
    Since the sitemaps are restricted, use the Selenium browser to visit the search page
    and extract scheme URLs directly from the DOM after JavaScript rendering. This will paginate
    through multiple pages to extract as many schemes as possible.
    """
    print("=========================================")
    print("PHASE 1: QUICKLY COLLECTING ALL URLS (Pagination)")
    print("Fetching URLs dynamically via Selenium pagination...")
    print("=========================================", flush=True)

    browser.get("https://www.myscheme.gov.in/search")
    time.sleep(5)
    
    found_urls = set()
    current_page = 1

    while True:
        print(f"[*] Scraping page {current_page}...", flush=True)
        
        # Scroll to ensure elements load
        browser.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(3)
        
        html = browser.page_source
        soup = BeautifulSoup(html, "html.parser")
        
        page_urls = set()
        for a in soup.find_all("a", href=True):
            if '/schemes/' in a['href']:
                href = a['href']
                url = href if href.startswith("http") else "https://www.myscheme.gov.in" + href
                
                # Filter out generic scheme links that aren't specific schemes
                if url != "https://www.myscheme.gov.in/schemes" and url != "https://www.myscheme.gov.in/schemes/":
                    # Only add if it's genuinely new
                    if url not in found_urls:
                        page_urls.add(url)
                        found_urls.add(url)
                        
                        # Add it immediately to the extraction queue!
                        if not collection.find_one({"source_url": url}):
                            url_queue.put(url)
        
        print(f"[*] Found URLs on page {current_page}. Total unique so far: {len(found_urls)}")

        # Try to click the "Next" button
        try:
            # The pagination on myscheme.gov.in usually has svgs for Next/Prev inside a specific container
            js_click_next = """
                let targetPagination = Array.from(document.querySelectorAll('ul')).find(ul => {
                    let lis = ul.querySelectorAll('li');
                    if (lis.length < 3) return false;
                    let hasNumbers = Array.from(lis).some(li => !isNaN(parseInt(li.innerText.trim())));
                    let hasSvgs = ul.querySelectorAll('svg.cursor-pointer').length > 0;
                    return hasNumbers && hasSvgs;
                });
                
                if (targetPagination) {
                    let svgs = Array.from(targetPagination.querySelectorAll('svg.cursor-pointer'));
                    if (svgs.length > 0) {
                        let nextBtn = svgs[svgs.length - 1]; // Assume the last SVG is the Next button
                        
                        let isDisabled = nextBtn.classList.contains('cursor-not-allowed') || 
                                         nextBtn.classList.contains('!cursor-not-allowed') ||
                                         nextBtn.classList.contains('opacity-50') ||
                                         nextBtn.parentElement.classList.contains('cursor-not-allowed') ||
                                         nextBtn.parentElement.classList.contains('opacity-50');
                                         
                        if (!isDisabled) {
                            nextBtn.scrollIntoView({behavior: "smooth", block: "center"});
                            return nextBtn;
                        }
                    }
                }
                return null;
            """
            
            # Execute the script to find and return the element (as a Selenium WebElement)
            next_element = browser.execute_script(js_click_next)
            
            if next_element:
                time.sleep(2) # Give it a moment after scrolling to center
                try:
                    next_element.click()
                except Exception:
                    # React needs a bubbling click event
                    browser.execute_script("arguments[0].dispatchEvent(new MouseEvent('click', {bubbles: true, cancelable: true}));", next_element)
                
                time.sleep(5) # Wait for the next page of schemes to load
                current_page += 1
            else:
                # If the Next SVG has 'cursor-not-allowed', we've hit the very last page!
                print(f"[*] 'Next' button is disabled or not found. Reached the end at page {current_page}.", flush=True)
                break
                
        except Exception as e:
            print(f"[*] Error during pagination: {e}", flush=True)
            break
            
    print(f"[*] Done paginating. Found {len(found_urls)} unique scheme URLs.", flush=True)
    return list(found_urls)


def worker_llm_extractor(collection, url_queue):
    """
    This function runs in a background thread and consumes URLs specifically added 
    to the queue, rendering them in a background worker-browser and passing them to Ollama.
    """
    print("[THREAD] Booting up background AI-Extractor Browser...", flush=True)
    # Give the first URL time to be fetched in pagination
    time.sleep(10)
    
    worker_browser = setup_browser()
    count = 1
    
    while True:
        scheme_url = url_queue.get()
        if scheme_url == "DONE":
            url_queue.task_done()
            break
            
        # Optional check just in case added twice
        if collection.find_one({"source_url": scheme_url}):
            url_queue.task_done()
            continue

        print(f"\n[AI-WORKER] Deep scraping & analyzing {scheme_url}")
        
        try:
            worker_browser.get(scheme_url)
            time.sleep(3.5) # Wait for React DOM
        except Exception as e:
            print(f"      -> Worker crashed: {e}. Restoring...")
            try: worker_browser.quit()
            except: pass
            time.sleep(3)
            worker_browser = setup_browser()
            try:
                worker_browser.get(scheme_url)
                time.sleep(3.5)
            except Exception as e2:
                print(f"      -> Worker final skip: {e2}")
                url_queue.task_done()
                continue
                
        soup = BeautifulSoup(worker_browser.page_source, 'html.parser')
        for script in soup(["script", "style", "nav", "footer", "header", "svg", "img"]):
            script.extract()
        raw_text = " ".join(soup.stripped_strings)
        
        if len(raw_text) > 100:
            print(f"      -> Analying {len(raw_text)} chars with Ollama... (please wait)")
            structured_data = extract_scheme_details_with_ollama(raw_text, scheme_url)
            
            if structured_data:
                collection.update_one(
                    {"source_url": scheme_url}, 
                    {"$set": structured_data}, 
                    upsert=True
                )
                
                scheme_name = structured_data.get("name", "Unknown Name")
                print(f"      -> [SUCCESS] Saved to MongoDB! Scheme Name: {scheme_name}")
                print("-" * 50)
            else:
                print(f"      -> [!] Extraction failed or returned malformed data.")
        else:
            print("      -> [!] Failed to extract body from React component.")
            
        time.sleep(1) # Cooldown
        url_queue.task_done()
        count += 1
        
    worker_browser.quit()
    print("[THREAD] AI-Extractor finished all URLs.")

def setup_browser():
    options = uc.ChromeOptions()
    # options.add_argument('--headless=new')  # Removed headless mode so user can see it
    options.add_argument('--disable-gpu')
    options.add_argument('--no-sandbox')
    
    try:
        browser = uc.Chrome(options=options)
        browser.set_window_size(1920, 1080)
        
        # Override the quit method to safely ignore the WinError 6 exception on shutdown
        original_quit = browser.quit
        def safe_quit():
            try:
                original_quit()
            except OSError as e:
                # Silently catch "[WinError 6] The handle is invalid" generated by uc module
                pass
            except Exception:
                pass
        browser.quit = safe_quit
        
        return browser
    except Exception as e:
        print(f"Error launching browser: {e}")
        from selenium import webdriver
        from selenium.webdriver.chrome.options import Options
        chrome_options = Options()
        # chrome_options.add_argument('--headless=new') # Removed here too
        return webdriver.Chrome(options=chrome_options)



def extract_scheme_details_with_ollama(raw_text, source_url):
    import requests
    
    prompt = f"""
    Analyze the following raw text from a government scheme webpage and extract the information into a strict JSON format exactly like the example. 
    If a field is missing, use null or an empty array []. Do not include formatting like ```json. Return ONLY valid JSON.
    
    Expected Schema Format:
    {{
      "source_url": "{source_url}",
      "application_steps": "string",
      "benefits": "string",
      "category_tags": ["string"],
      "date_of_scheme_launch": "string or null",
      "description": "string",
      "eligibility": "string",
      "industry_tags": ["string"],
      "location_tags": ["string"],
      "name": "string",
      "scheme_id": "string or null",
      "target_audience_tags": ["string"]
    }}
    
    Text Data from Web Scrape:
    {raw_text[:8000]}
    """
    
    payload = {
        "model": "mistral",  # Changed to mistral since you already have it downloaded
        "prompt": prompt,
        "stream": False,
        "format": "json"  # Ollama natively forces JSON output with this flag
    }
    
    try:
        response = requests.post("http://localhost:11434/api/generate", json=payload)
        response.raise_for_status()
        
        result_json = response.json()
        text_resp = result_json.get("response", "").strip()
        
        # Sometimes small artifacts are left over, ensure it cleans them
        text_resp = text_resp.replace("```json", "").replace("```", "").strip()
        
        try:
            return json.loads(text_resp)
        except json.JSONDecodeError as je:
            print(f"      -> [!] Ollama JSON parsing error: {je}")
            print(f"      -> [!] Raw Ollama output: {text_resp}")
            return None
            
    except Exception as e:
        print(f"      -> [!] Ollama API connection/extraction failed: {e}")
        return None

def main():
    if not all([MONGO_URL, WEBSITE_URL]):
        print("Ensure MONGO_URL and WEBSITE_URL are set in .env")
        return

    print("Connecting to MongoDB...", flush=True)
    collection = get_db_collection()
            
    print("Launching Main Headless Browser... (this may take up to 10 seconds)", flush=True)
    browser = setup_browser()
    
    url_queue = queue.Queue()
    
    # Spawn background LLM thread
    t = threading.Thread(target=worker_llm_extractor, args=(collection, url_queue))
    t.daemon = True
    t.start()

    scheme_urls = scrape_sitemap_schemes(collection)
    if scheme_urls:
         for u in scheme_urls: url_queue.put(u)
    else:
        scheme_urls = extract_urls(browser, collection, url_queue)

    if not scheme_urls:
        print("No scheme URLs found. Ensure the WAF hasn't blocked the Selenium footprint.")
        url_queue.put("DONE")
        browser.quit()
        return

    print("\n[MAIN] Pagination loop complete, all URLs fetched.")
    print(f"[MAIN] Closing main browser. Waiting for AI-worker to finish the {url_queue.qsize()} remaining links in queue...")
    
    browser.quit()
    url_queue.put("DONE")
    
    # Block script from terminating until the AI queue completely finishes processing
    url_queue.join()
    t.join()
    
    print("\nEntire Website AI Structuring & Web Scraping Complete!")

if __name__ == "__main__":
    main()